title: Siwakorn Siwaworawet
logo: /assets/img/headshot_circle.png
# The symbol '>' lets us write multiple lines of HTML text below
description: >
  <center>
    <a href="resume.pdf">Resume</a> | 
    <a href="https://www.linkedin.com/">LinkedIn</a> | 
    <a href="mailto:siwakorn.siwaworawet@gmail.com">Email</a>
  </center>
  <br>
  Civil Engineering graduate from <strong>KMUTT</strong>. Skilled in Structural Analysis (SAP2000, Abaqus), Design Software (AutoCAD, Revit), and Site Engineering.
  <br><br>
  I love solving complex structural challenges. :)
  <br><br>
  <strong>Email:</strong> siwakorn.siwaworawet@gmail.com

show_downloads: false
theme: jekyll-theme-minimal
